swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "https://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - https
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: User Transactions API
      description: API for fetching the list of transactions for a specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: View Transaction Details
      description: API for viewing the details of a specific transaction
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Unique ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetailResponse"
        "400":
          description: Invalid Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: Modify Transaction
      description: API for modifying a transaction
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdateDetail"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/TransactionUpdateResponse"
        "400":
          description: Invalid Fields or Transaction ID
        "401":
          description: Unauthorized Access
        "404":
          description: Transaction Not Found
        "500":
          description: Internal Server Error
  /user/transaction/add:
    post:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: User Transactions API ADD
      description: Create a new transaction with provided informations
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Transaction Informations Payload
          required: true
          schema:
            $ref: "#/definitions/TransactionAdd"
      produces:
        - application/json
      responses:
        "201":
          description: Successfully created transaction
          schema:
            $ref: "#/definitions/TransactionAddResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: Transactions successfully retrieved
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uuid
              description: This transaction's UUID
              example: 823cc0mv3344H6464
            date:
              type: string
              format: date-time
              description: Transaction date and time
              example: 2024-02-16T09:14:02.766+00:00
            description:
              type: string
              description: Transaction description
              example: Total Energy Station
            amount:
              type: integer
              description: Amount of transaction in cents
              example: 740
            balance:
              type: integer
              description: Amount of account in cents
              example: 485198
            type:
              type: string
              description: The method used by the user in order to pay (electronic, cash, etc...)
              example: Electronic
            category:
              type: string
              description: The category of this transaction (Tony | Personal | etc...)
              example: Transport
            notes:
              type: string
              description: Note added by user. Empty by default.
              example: Gasoline
  TransactionUpdateResponse:
    type: object
    properties:
      status:
        type: integer
        description: Response status code from the API
        example: 200
      message:
        type: string
        description: Response message from the API
        example: Transaction successfully updated
  TransactionDetailResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: This transaction's UUID
        example: 823cc0mv3344H6464
      date:
        type: string
        format: date-time
        description: Transaction date and time
        example: 2024-02-16T09:14:02.766+00:00
      description:
        type: string
        description: Transaction description
        example: Total Energy Station
      amount:
        type: integer
        description: Amount of transaction in cents
        example: 740
      balance:
        type: integer
        description: Amount of account in cents
        example: 485198
      type:
        type: string
        description: The method used by the user in order to pay (electronic, cash, etc...)
        example: Electronic
      category:
        type: string
        description: The category of this transaction (Tony | Personal | etc...)
        example: Transport
      notes:
        type: string
        description: Note added by user. Empty by default.
        example: Gasoline
  TransactionUpdateDetail:
    type: object
    properties:
      amount:
        type: number
        description: Updated transaction amount
        example: 59.99
      description:
        type: string
        description: Updated transaction description
        example: celio
      note:
        type: string
        description: Updated transaction description
        example: jean
      type:
        type: string
        description: Transaction type
        example: Achat
      category:
        type: string
        description: The category of this transaction (Tony | Personal | etc...)
        example: Achat
  TransactionAdd:
    type: object
    properties:
      description:
        type: string
        description: description transaction
        example: Boulangerie
      amount:
        type: integer
        description: Amount of transaction in cents
        example: 1.90
      type:
        type: string
        description: Transaction type
        example: restaurant
      category:
        type: string
        description: The category of this transaction (Tony | Personal | etc...)
        example: Vie quotidienne
      note:
        type: string
        description: Note added by user. Empty by default.
        example: Pain suisse
  TransactionAddResponse:
    type: object
    properties:
      status:
        type: integer
        example: 201
        description: Query status
      message:
        type: string
        example: Successfully created transaction
        description: Query message
